name: Continuous Delivery
run-name: ${{ github.actor }} is testing out continuous delivery

on: [push]

jobs:
    Continous-delivery-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:latest .
            - name: Push to Docker Hub
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:latest
            - name: Log in to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_TOKEN }}
            - name: Push to Github Container Registry
              run: |
                docker tag ${{ secrets.DOCKER_USERNAME }}/sysinfo-api:latest ghcr.io/${{ github.repository_owner }}/sysinfo-api:latest
                docker push ghcr.io/${{ github.repository_owner }}/sysinfo-api:latest